import { Html, Head, Main, NextScript } from 'next/document';
import { ColorModeScript } from '@chakra-ui/react';

export default function Document() {
    return (
        <Html>
            <Head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap"
                    rel="stylesheet"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@600&display=swap"
                    rel="stylesheet"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Space+Mono&display=swap"
                    rel="stylesheet"
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Thin.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Thin.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ThinItalic.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ThinItalic.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ExtraLight.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ExtraLight.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ExtraLightItalic.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ExtraLightItalic.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-LightItalic.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-LightItalic.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Regular.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Regular.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Italic.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Italic.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Medium.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Medium.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-MediumItalic.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-MediumItalic.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Semibold.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Semibold.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-SemiboldItalic.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-SemiboldItalic.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Bold.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Bold.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-BoldItalic.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-BoldItalic.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ExtraBold.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ExtraBold.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ExtraBoldItalic.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-ExtraBoldItalic.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Black.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-Black.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-BlackItalic.woff"
                    type="font/woff"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-BlackItalic.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-roman.var.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay-italic.var.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    as="font"
                    href="/fonts/InterDisplay.var.woff2"
                    type="font/woff2"
                    crossOrigin=""
                />
            </Head>
            <body style={{ overflowX: 'hidden' }}>
                <ColorModeScript initialColorMode="dark" />
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
